apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "common.names.fullname" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels: {{- include "common.labels.standard" . | nindent 4 }}
  {{- if .Values.commonLabels }}
  {{- include "common.tplvalues.render" ( dict "value" .Values.commonLabels "context" $ ) | nindent 4 }}
  {{- end }}
  {{- if .Values.commonAnnotations }}
  annotations: {{- include "common.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
  {{- end }}
data:
  APP_DEBUG: {{ .Values.image.debug | quote }}
  APP_ENV: {{ .Values.shopwareAppEnv | quote }}
  APP_URL: {{ .Values.shopwareAppUrl | quote }}

  DATABASE_HOST: {{ include "shopware.databaseHost" . | quote }}

  {{- if or .Values.elasticsearch.enabled .Values.externalElasticsearch.host }}
  SHOPWARE_ES_ENABLED: "true"
  SHOPWARE_ES_INDEXING_ENABLED: "true"
  SHOPWARE_ES_HOSTS: {{ template "shopware.elasticsearch.fullname" . }}
  {{- end }}
  SHOPWARE_HTTP_CACHE_ENABLED: {{ .Values.httpCache.enabled | quote }}
  SHOPWARE_HTTP_DEFAULT_TTL: {{ .Values.httpCache.defaultTtl | quote }}
  DISABLE_ADMIN_WORKER: {{ .Values.consumer.enabled | quote }}
  INSTALL_LOCALE: {{ .Values.shopwareLocale | quote }}
  INSTALL_CURRENCY: {{ .Values.shopwareCurrency | quote }}
  INSTALL_ADMIN_USERNAME: {{ .Values.shopwareUsername | quote }}
  CACHE_ADAPTER: {{ .Values.cache.adapter | quote }}
  REDIS_CACHE_HOST: {{ include "shopware.cacheHost" . }}
  REDIS_CACHE_PORT: {{ include "shopware.cachePort" . | quote }}
  REDIS_CACHE_DATABASE: {{ .Values.cache.database | quote }}
  SESSION_ADAPTER: {{ .Values.session.adapter | quote }}
  REDIS_SESSION_HOST: {{ include "shopware.cacheHost" . }}
  REDIS_SESSION_PORT: {{ include "shopware.cachePort" . | quote }}
  REDIS_SESSION_DATABASE: {{ .Values.session.database | quote }}
  {{- if .Values.activePlugins }}
  ACTIVE_PLUGINS: {{ .Values.activePlugins | quote }}
  {{- end }}
