apiVersion: v1
kind: Secret
metadata:
  name: {{ template "common.names.fullname" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels: {{- include "common.labels.standard" . | nindent 4 }}
    {{- if .Values.commonLabels }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.commonLabels "context" $ ) | nindent 4 }}
    {{- end }}
  {{- if .Values.commonAnnotations }}
  annotations: {{- include "common.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
  {{- end }}
type: Opaque
data:
  INSTANCE_ID: {{ default (include "shopware.randomSecret" .) .Values.shopwareInstanceId | b64enc | quote }}
  APP_SECRET: {{ default (include "shopware.randomSecret" .) .Values.shopwareAppSecret | b64enc | quote }}
  DATABASE_URL: {{ include "shopware.databaseUrl" . | b64enc | quote  }}
  MAILER_URL: {{ .Values.mailerUrl | b64enc | quote }}

  {{- if .Values.shopwarePassword }}
  INSTALL_ADMIN_PASSWORD: {{ .Values.shopwarePassword | b64enc | quote }}
  {{- else }}
  INSTALL_ADMIN_PASSWORD: {{ randAlphaNum 10 | b64enc | quote }}
  {{- end }}